server:
  port: 8080

spring:
  application:
    name: algoViz

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.hdkwlhukwmrifmagvxhi.supabase.co:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Aigoviz2026}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Cấu hình Swagger OpenAPI UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

